[package]
name = "bevy_modapi"
edition.workspace = true
version.workspace = true

[dependencies]
bevy_modapi_macros = { path = "../bevy_modapi_macros" }
bevy_modtypes = { path = "../bevy_modtypes" }
bevy_modsdk = { path = "../bevy_modsdk" }

