[package]
name = "modapi_macros"
edition.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
bevy = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
