[package]
name = "modapi"
edition.workspace = true
version.workspace = true

[package.metadata.component]
package = "bevy:mod-api"

[package.metadata.component.target]
world = "src/wit/world.wit"

[dependencies]
modapi_macros = { path = "../modapi_macros" }
modtypes = { path = "../modtypes" }

