[package]
name = "game_mod"
edition.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]  # Mods are compiled as WebAssembly modules

[dependencies]
bevy_math = "0.16"
modapi = { path = "../../../modapi" }
game_sdk = { path = "../game_sdk" }
