[package]
name = "host"
edition.workspace = true
version.workspace = true

[dependencies]
bevy = { workspace = true }
modruntime = { path = "../../../modruntime" }
serde = { workspace = true }
linkme = { workspace = true }
bincode = { workspace = true }
