[package]
name = "host"
edition.workspace = true
version.workspace = true

[dependencies]
bevy = { workspace = true }
bevy_modruntime = { path = "../../../bevy_modruntime" }
serde = { workspace = true }
bincode = { workspace = true }
linkme = { workspace = true }
