[package]
name = "modsdk_macros"
edition.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = { workspace = true }
syn = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
