[package]
name = "game_sdk"
edition.workspace = true
version.workspace = true

[dependencies]
bevy_math = { version = "0.16", features = ['serialize'] }
modsdk = { path = "../../../modsdk" }
serde = { workspace = true }
bincode = { workspace = true }
