[package]
name = "game_sdk"
edition.workspace = true
version.workspace = true

[dependencies]
bevy_math = { version = "0.16", features = ['serialize'] }
bevy_modsdk = { path = "../../../bevy_modsdk" }
serde = { workspace = true }
